### ISSUE TITLE
Discussion: cortex benchmark cli

### ISSUE THREAD

**Issue by hiro-v** [janhq/cortex#610] opened 2024-05-24 06:28 UTC
**Motivation**
- Standardized way to get performance metrics as defined in [Databrick LLM inference](https://www.databricks.com/blog/llm-inference-performance-engineering-best-practices)
- Standardized way to get hardware data as defined in [Notion for hardware data](https://www.notion.so/jan-ai/Hiro-Scratchpad-on-hardware-stats-af715e64c9a64a6c939d840effcb713c?pvs=4#994aea6cee9f44cd9d33717135be865e) related to motherboard, CPU, GPU, memory, disk, psu, chassis.
- Standardized way to get model runtime and kernel data during inference.

**Discussion**
- Start cortex
```
# 1. Install the NPM package
npm i -g @janhq/cortex

# 2. Initialize a compatible engine
cortex init

# 3. Download a GGUF model from Hugging Face
#    Models save to $(npm list -g)/node_modules
cortex models pull janhq/TinyLlama-1.1B-Chat-v1.0-GGUF

# 4. Load the model
cortex models start janhq/TinyLlama-1.1B-Chat-v1.0-GGUF
```
- Start benchmark cli (not bundled with cortex) which is written in NodeJS
```yaml
api:
    url: <cortex_url>
    api_key: <>
prompts:
    min: 1024
    max: 2048
    samples: 10
output: json
hardware: [cpu, gpu, psu, chassis, ram]
```

```bash
cortex-benchmark shoot
```
```mermaid
sequenceDiagram
    participant User
    participant Program
    participant SystemInfo
    participant OpenAI_API
    participant Monitor

    User->>+Program: Start (api_url, api_key, monitor_interval)
    Program->>+SystemInfo: Retrieve Hardware Metadata
    SystemInfo-->>-Program: Metadata

    loop Benchmarking Loop
        Program->>+OpenAI_API: Send Prompt (1024-2048 tokens)
        OpenAI_API-->>-Program: Response (latency, tokens)
    end

    loop Monitoring Loop
        Program->>+Monitor: Check CPU & Memory
        Monitor-->>-Program: Usage Data
    end

    Program->>+Program: Calculate Percentiles
    Program-->>-User: Display Metrics and Usage

```
1. Resource Metadata Retrieval: At the start of the program, it gathers detailed metadata about the CPU, memory, disks, and graphics systems.
2. OpenAI API compatible Benchmarking: The program tests the OpenAI API by submitting prompts of varying token lengths (from 1024 to 2048 tokens) to measure latency and time per output token. It iterates over 10 different lengths, increasing by 128 tokens each iteration.
3. Resource Monitoring: System resources (CPU and memory usage) are monitored at user-specified intervals, allowing for ongoing observation without impacting the benchmark tests.
4. Metrics Calculation: At the end of the monitoring period, the program calculates and displays the 50th, 75th, and 99th percentiles for CPU and memory usage, providing insights into the system's performance under load.

**Resources**

**Comment by 0xSage** [comment] 2024-07-01 05:06
closing as dupe of #798

**Closed by 0xSage** 2024-07-01 05:06 UTC
